ASide:
  - Room: "ch1-memory-00"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Right
      Idx: 0
      Kind: unknown
    InternalEdges:
    - Warp: "crane-void-00"
      To: "main"
      ReqOut:
        Dashes: zero
    Tweaks:
    - Name: "moveBlock"
      Update:
        Add: true
        X: 208
        Y: 96
        Width: 16
        Height: 16
        Direction: Up
        CanSteer: true
        Fast: true
  - Room: "crane-void-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
  - Room: "crane-void-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Dashes: one
        Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 120
        Y: 40
  - Room: "crane-void-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 5
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    InternalEdges:
    - To: "top"
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Dashes: two
        Difficulty: expert
    Subrooms:
    - Room: "top"
      Holes:
      - Side: Up
        Idx: 0
        Kind: none
      - Side: Up
        Idx: 1
        Kind: none
      - Side: Up
        Idx: 2
        Kind: out
      - Side: Up
        Idx: 3
        Kind: none
      - Side: Up
        Idx: 4
        Kind: none
      - Side: Up
        Idx: 5
        Kind: none
      - Side: Up
        Idx: 6
        Kind: none 
      - Side: Left
        Idx: 0
        Kind: none
      - Side: Left
        Idx: 1
        Kind: none
      - Side: Right
        Idx: 0
        Kind: none
      - Side: Right
        Idx: 1
        Kind: none
      - Side: Right
        Idx: 2
        Kind: none
    Tweaks:
    - Name: "jumpthru"
      ID: 197
      Update: 
        Remove: true
    - Name: "spawn"
      Update:
        Add: true
        X: 112
        Y: 40
    - Name: SafeRespawnCrumble/SafeRespawnCrumble
      Update:
        Add: true
        X: 104
        Y: 40
        Width: 8
  - Room: "crane-void-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
  - Room: "crane-void-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
  - Room: "crane-void-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Dashes: two
        Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 264
        Y: 32
    - Name: "SafeRespawnCrumble/SafeRespawnCrumble"
      Update: 
        Add: true
        X: 256
        Y: 32
        Width: 8
  - Room: "crane-void-06"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Up
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 4
      Kind: in
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
  - Room: "crane-void-07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 10
      Kind: none
    - Side: Down
      Idx: 11
      Kind: none
    - Side: Down
      Idx: 12
      Kind: in
    - Side: Down
      Idx: 13
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
  - Room: "crane-void-08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
  - Room: "crane-void-09"
    Holes:
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
  - Room: "crane-void-10"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Warp: "memory-01"
      To: "main"
      ReqOut:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
  - Room: "memory-01"
    End: true
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Left
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Right
      Idx: 0
      Kind: unknown
    Tweaks:
    - Name: "spring"
      Update: 
        Add: true
        X: 376
        Y: 152
  - Room: "crane-void-golden" #golden rooms lol
    Holes:
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
      ReqIn: 
        Dashes: zero
    Tweaks:
    - Name: "infiniteStar"
      Update:
        Add: true
        X: 272
        Y: 120
    - Name: "infiniteStar"
      Update:
        Add: true
        X: 32
        Y: 128
    - Name: "jumpThru"
      Update:
        Add: true
        X: 0
        Y: 160
        Width: 56
        Texture: dream
  - Room: "crane-void-golden-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Left
      Idx: 5
      Kind: none
    - Side: Left
      Idx: 6
      Kind: none
    - Side: Left
      Idx: 7
      Kind: none
    - Side: Left
      Idx: 8
      Kind: none
    - Side: Left
      Idx: 9
      Kind: none
    - Side: Left
      Idx: 10
      Kind: none
    - Side: Left
      Idx: 11
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 5
      Kind: none
    - Side: Right
      Idx: 6
      Kind: none
    - Side: Right
      Idx: 7
      Kind: none
    - Side: Right
      Idx: 8
      Kind: none
    - Side: Right
      Idx: 9
      Kind: none
    - Side: Right
      Idx: 10
      Kind: inout
  - Room: "crane-void-golden-02"
    End: true
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    ReqEnd:
      Or:
      - Dashes: one
      - Dashes: zero 
        Difficulty: perfect
    Tweaks:
    - Name: "spring"
      Update: 
        Add: true
        X: 152
        Y: 264
    - Name: "spring"
      Update: 
        Add: true
        X: 160
        Y: 112