ASide:
  - Room: "memory-00"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Right
      Idx: 0 
      Kind: unknown
    InternalEdges:
    - Warp: "peace-00"
      To: "main"
      ReqOut:
        Dashes: zero
    Tweaks:
    - Name: "moveBlock"
      Update:
        Add: true
        X: 224
        Y: 144
        Width: 16
        Height: 16
        Direction: Up
        CanSteer: true
        Fast: true
  - Room: "peace-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut: 
        Dashes: one
      ReqIn: 
        Dashes: one
  - Room: "peace-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or: 
        - Dashes: two
          Difficulty: normal
        - Dashes: one
          Difficulty: hard
      ReqIn:
        Dashes: two
        Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 296
        Y: 48
    - Name: SafeRespawnCrumble/SafeRespawnCrumble
      Update:
        Add: true
        X: 296
        Y: 48
        Width: 8
  - Room: "peace-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Up 
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or: 
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Dashes: zero
        Difficulty: normal
    Tweaks:
    - Name: "jumpThru"
      ID: 111
      Update:
        Width: 16
  - Room: "peace-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
#    InternalEdges:
#    - Split: LeftToRight
#      ReqOut:
#        Dashes: one
#        Difficulty: hard
#      ReqIn:
#        Dashes: two
#        Difficulty: expert
  - Room: "peace-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
      ReqOut:
         Dashes: one
         Difficulty: hard
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
  - Room: "peace-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
         Dashes: one
         Difficulty: hard
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
  - Room: "peace-06"
    Holes:
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: out
      ReqOut:
         Dashes: one
         Difficulty: hard
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0 
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
  - Room: "peace-07"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
         Dashes: one
         Difficulty: hard
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
  - Room: "ch2-peace-075"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut: 
        Dashes: one
        Difficulty: normal
      ReqIn:
        Dashes: zero
        Difficulty: normal
  - Room: "peace-08"
    Holes:
    - Side: Left
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Dashes: two
        Difficulty: perfect
    Tweaks:
    - Name: "refill"
      ID: 1368
      Update:
        Y: 136
  - Room: "peace-09"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout 
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Or:
        - Dashes: two
          Difficulty: normal
        - Dashes: one
          Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 32
        Y: 32
    - Name: SafeRespawnCrumble/SafeRespawnCrumble
      Update:
        Add: true
        X: 24
        Y: 32
        Width: 8
  - Room: "peace-10"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Or:
        - Dashes: two
          Difficulty: normal
        - Dashes: zero
          Difficulty: hard
    Tweaks:
    - Name: "jumpThru"
      ID: 1584
      Update:
        Width: 24
  - Room: "peace-11"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Or:
        - Dashes: two
          Difficulty: normal
        - Dashes: one
          Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 128
        Y: 48
  - Room: "peace-12"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Or:
        - Dashes: two
          Difficulty: normal
        - Dashes: one
          Difficulty: hard
    Tweaks:
    - Name: "jumpThru"
      ID: 2204
      Update:
        Width: 48
  - Room: "peace-13"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Or:
        - Dashes: two
          Difficulty: normal
        - Dashes: one
          Difficulty: hard
  - Room: "peace-14"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
  - Room: "peace-15"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Warp: "ch3-crane-pink-00"
      To: "main"
      ReqOut:
        Dashes: zero
  - Room: "ch3-crane-pink-00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
  - Room: "crane-pink-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Dashes: two
        Difficulty: perfect
  - Room: "crane-pink-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: none
  - Room: "crane-pink-03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Dashes: two
        Difficulty: expert
    Tweaks:
    - Name: "jumpThru"
      ID: 1604
      Update:
        Remove: true
  - Room: "crane-pink-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
  - Room: "crane-pink-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
  - Room: "crane-pink-06"
    End: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none