ASide:
  - Room: "E-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 1
      Kind: unknown
    - Side: Down
      Idx: 2
      Kind: unknown
    - Side: Down
      Idx: 3
      Kind: unknown
    - Side: Down
      Idx: 3
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 1
      Kind: inout
      ReqBoth:
        Dashes: one
        Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 32
        Y: 152
  - Room: "E-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
  - Room: "c-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 32
        Y: 152
  - Room: "E-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
        Difficulty: hard
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 1
      Kind: unknown
    - Side: Down
      Idx: 2
      Kind: unknown
    - Side: Down
      Idx: 3
      Kind: unknown
    - Side: Down
      Idx: 4
      Kind: unknown
  - Room: "E-06"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: unknown
      ReqIn: 
        Dashes: two
        Difficulty: hard
    - Side: Down
      Idx: 1
      Kind: unknown
    - Side: Down
      Idx: 2
      Kind: unknown
    - Side: Down
      Idx: 3
      Kind: unknown
    - Side: Down
      Idx: 4
      Kind: unknown
    - Side: Down
      Idx: 5
      Kind: unknown
    - Side: Down
      Idx: 6
      Kind: unknown
    - Side: Down
      Idx: 7
      Kind: unknown
    - Side: Down
      Idx: 8
      Kind: unknown
    - Side: Down
      Idx: 9
      Kind: unknown
    - Side: Down
      Idx: 10
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 1
      Kind: unknown
    - Side: Up
      Idx: 2
      Kind: unknown
    - Side: Up
      Idx: 3
      Kind: unknown
    - Side: Up
      Idx: 4
      Kind: unknown
  - Room: "E-Cassette"
    End: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown